apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ${namespace}
  labels:
    app: nginx
spec:
  replicas: ${replicas}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ${image}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: ${volume_name}
              mountPath: ${mountPath}
              subPath: ${subPath}
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 252Mi
            limits:
              cpu: 200m
              memory: 512Mi
      volumes:
        - name: ${volume_name}
          configMap:
            name: ${configMap_name}
