apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ${namespace}
  labels:
    app: nginx
spec:
  type: ${service_type}
  selector:
    app: ${pod_selector}
  ports:
    - name: http
      protocol: TCP
      port: ${service_port}
      targetPort: {container_port}
